base/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from base.views import SallesView


urlpatterns = patterns('',

                       url(r'^salle/(?P<regroupement>\w+)/$', SallesView.as_view(), name='liste_salle'),
)

site_vo_vietnam/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.generic import TemplateView
from registration.backends.default.views import RegistrationView
from django.contrib.auth import views as auth_views
from base.views import SallesView

admin.autodiscover()
from django.conf import settings


urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'site_vo.views.home', name='home'),
                       # url(r'^site_vo/', include('site_vo.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                        # url(r'^blog/', include('zinnia.urls')),
                       # Uncomment the next line to enable the admin:
                       #(r'^forum/account/', include('django_authopenid.urls')),
                       url(r'^calendar/', include('calendarium.urls')),
                       (r'^forum/account/', include('registration.backends.default.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       # url(r'^admin_tools/', include('admin_tools.urls')),
                        url(r'^salles/', include('base.urls')),
                       (r'^forum/', include('djangobb_forum.urls', namespace='djangobb')),
                       url(r'^comments/', include('django.contrib.comments.urls')),
                       (r'^forum/pm/', include('django_messages.urls')),
                       (r'^tinymce/', include('tinymce.urls')),
                       url(r'^password/reset/$', auth_views.password_reset, name='auth_password_reset'),
                       url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
                           auth_views.password_reset_confirm,
                           name='auth_password_reset_confirm'),
                       url(r'^password/reset/complete/$',
                           auth_views.password_reset_complete,
                           name='auth_password_reset_complete'),
                       url(r'^password/reset/done/$',
                           auth_views.password_reset_done,
                           name='auth_password_reset_done'),
                       url(r'^password/$', 'django.contrib.auth.views.password_change',
                           {'template_name': 'authopenid/password_change_form.html'}, name='auth_password_change'),
                       (r'^account/', include('django.contrib.auth.urls')),
                       url(r'^signin/$', 'django.contrib.auth.views.login', {'template_name': 'authopenid/signin.html'},
                           name='user_signin'),
                       url(r'^signup/$', RegistrationView.as_view(), name='registration_register', ),
                       url(r'^signup/complete/$',
                           TemplateView.as_view(template_name='registration/registration_complete.html'),
                           name='registration_complete'),
                       url(r'^signup/closed/$',
                           TemplateView.as_view(template_name='registration/registration_closed.html'),
                           name='registration_disallowed'),
                       url(r'^', include('cms.urls')),




)

if settings.DEBUG:
    urlpatterns = patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'', include('django.contrib.staticfiles.urls')), ) + urlpatterns

base/models.py
# coding=utf-8
import htmlentitydefs
from django.utils.translation import ugettext_lazy as _
import re
from cms.models import CMSPlugin
from . import geocode
from django.db import models
from django.utils.html import strip_tags
from django.conf import settings
import logging
import HTMLParser
logger = logging.getLogger(__name__)
class DjangoBBModel(CMSPlugin):
    nb_last_post = models.IntegerField(u"nombre de post", default=5)


class AgendaModel(CMSPlugin):
    nb_last_event = models.IntegerField(u'nombre d\'event', default=3)


class EntryZiniaCmsPlugins(CMSPlugin):
    nb_last_post = models.IntegerField(u"nombre de post", default=3)


class Professeur(models.Model):
    nom = models.CharField(u'Nom', max_length=50)
    prenom = models.CharField(u'Prénom', max_length=50)
    date_naissance = models.DateField(u"Date de naissance", null=True, blank=True)
    date_creation = models.DateTimeField(auto_now_add=True, editable=False)
    date_update = models.DateTimeField(auto_now=True, auto_now_add=True, editable=False)

    def __unicode__(self):
        return u"%s %s" % (self.nom, self.prenom)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.pk:
            self.pk = Professeur.objects.last().pk + 1
        super(Professeur, self).save(force_insert, force_update, using, update_fields)


    class Meta:
        verbose_name = u"Professeur"
        verbose_name_plural = u"Professeurs"


class PaysModel(models.Model):
    label = models.CharField(u"nom pays", max_length=50)

    def __unicode__(self):
        return self.label


class RegroupementSalle(models.Model):
    nom = models.CharField(max_length=60, null=True)
    pays = models.ForeignKey(PaysModel, null=True)

    def __unicode__(self):
        return u"{} {}".format(self.nom, self.pays)

class ListeProfesseur(CMSPlugin):
    pass

class ListeSalle(CMSPlugin):
    pays = models.ForeignKey(PaysModel)

class Salle(models.Model):
    nom = models.CharField(u'Nom', max_length=50)
    professeurs = models.ManyToManyField(Professeur, null=True, blank=True)
    horaire = models.TextField(u"Horaire", null=True, blank=True)
    adresse = models.CharField(u"adresse", max_length=500, null=True)
    description = models.TextField(u'description', null=True, blank=True)
    date_creation = models.DateTimeField(auto_now_add=True, editable=False)
    date_update = models.DateTimeField(auto_now=True, auto_now_add=True, editable=False)
    ville = models.CharField(u"nom ville", null=True, max_length=200)
    pays = models.ForeignKey(PaysModel)
    secteur = models.ForeignKey(RegroupementSalle, null=True, blank=True)

    computed_address = models.CharField(_('Computed address'), max_length=255, null=True, blank=True)
    latitude = models.FloatField(_('Latitude'), null=True, blank=True)
    longitude = models.FloatField(_('Longitude'), null=True, blank=True)
    geocode_error = models.BooleanField(_('Geocode error'), default=False)

    @property
    def adresse_plain(self):
        a = re.sub(r'\r\n|\r|\n|&nbsp|;', ' ', strip_tags(self.adresse))
        html_parser = HTMLParser.HTMLParser()
        unescaped = html_parser.unescape(a)
        a = decodeHtmlText(unescaped)
        return a

    def __unicode__(self):
        return self.nom

    def marker(self):
        url = '/salles/salle/{}/#{}'
        if self.secteur:
            url = url.format(self.secteur.pk, self.pk)
        else:
            return None
        return u'[\"{}\", {}, {}, \'{}\']'.format(self.nom, self.latitude, self.longitude, url)

    def fill_geocode_data(self):
        if not self.adresse_plain:
            self.geocode_error = True
            return
        try:
            do_geocode = getattr(settings, "EASY_MAPS_GEOCODE", geocode.google_v3)
            result = do_geocode(self.adresse_plain)
            if result:
                self.computed_address, (self.latitude, self.longitude,) = result
                self.geocode_error = False
            else:
                self.geocode_error = True
        except geocode.Error as e:
            try:
                logger.error(e)
            except Exception:
                logger.error("Geocoding error for address %s", self.adresse_plain)

            self.geocode_error = True
            # TODO: store the exception

    def save(self, *args, **kwargs):
        # fill geocode data if it is unknown
        if (self.longitude is None) or (self.latitude is None):
            self.fill_geocode_data()
        if self.pk:
            s = Salle.objects.get(pk=self.pk)
            if self.adresse_plain != s.adresse_plain:
                self.fill_geocode_data()
        else:
            self.pk = Salle.objects.last().pk + 1
        super(Salle, self).save(*args, **kwargs)

def decodeHtmlText(html):
    """
    Given a string of HTML that would parse to a single text node,
    return the text value of that node.
    """
    # Fast path for common case.
    if html.find("&") < 0: return html
    return re.sub(
        '&(?:#(?:x([0-9A-Fa-f]+)|([0-9]+))|([a-zA-Z0-9]+));',
        _decode_html_entity,
        html)

def _decode_html_entity(match):
    """
    Regex replacer that expects hex digits in group 1, or
    decimal digits in group 2, or a named entity in group 3.
    """
    hex_digits = match.group(1)  # '&#10;' -> unichr(10)
    if hex_digits: return unichr(int(hex_digits, 16))
    decimal_digits = match.group(2)  # '&#x10;' -> unichr(0x10)
    if decimal_digits: return unichr(int(decimal_digits, 10))
    name = match.group(3)  # name is 'lt' when '&lt;' was matched.
    if name:
        decoding = (htmlentitydefs.name2codepoint.get(name)
            # Treat &GT; like &gt;.
            # This is wrong for &Gt; and &Lt; which HTML5 adopted from MathML.
            # If htmlentitydefs included mappings for those entities,
            # then this code will magically work.
            or htmlentitydefs.name2codepoint.get(name.lower()))
        if decoding is not None: return unichr(decoding)
    return match.group(0)

base/forms.py
import re
from registration.forms import RegistrationFormUniqueEmail


class RegistrationFormUtfUsername(RegistrationFormUniqueEmail):
    '''
    Allowed UTF8 logins with space
    '''
    def __init__(self, *args, **kwargs):
        super(RegistrationFormUtfUsername, self).__init__(*args, **kwargs)
        self.fields['username'].regex = re.compile(r"^[\w\s-]+$", re.UNICODE)

base/views.py
# Create your views here.
from django.views.generic import TemplateView, DetailView
from base.models import RegroupementSalle


class SallesView(DetailView):
    template_name = 'base/liste_salle.html'
    model = RegroupementSalle
    pk_url_kwarg = 'regroupement'

base/templates/base/actualite_important.html
<div class="panel panel-default">
  <div class="panel-body">
    {% for post in posts %}
        {% if forloop.first %}
            <article class="showing">
            {% if post.image %}
            <div class="showcase-image">
                    <img src="{{ post.image.url }}">
                </div>
            {% endif %}

                <div class="showcase-texts" {% if not post.image %}
                style="width: 100%;"
                {% endif %} >

                    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>

                    {{ post.html_content|safe}}
                </div>
            </article>
        {% else %}
            {% if forloop.counter0 == 1 %}
                <section id="other">
            {% endif %}
        <article>

            <h2> <a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>

             {{ post.html_content|safe}}
        </article>
        {% if forloop.last %}
            </section>
        {% endif %}
        {% endif %}
    {% endfor %}
  </div>
</div>

base/templates/base/actualite_inter_national.html
<div class="actus row ">
    <ul class="nav nav-tabs col-sm-12">
        <li class="active"><a href="#international" data-toggle="tab">Actualités internationales</a></li>
        <li><a href="#national" data-toggle="tab">Actualités nationales</a></li>
    </ul>
</div>
<div class="tab-content">
    <div class="tab-pane active" id="international">
        <div class="row news">
            {% for post in posts_inter %}
                <div class="col-sm-3">
                    <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                    {% if post.image %}
                        <img src="{{ post.image.url }}" alt=""/>
                    {% endif %}
                    {{ post.html_content|safe }}
                </div>

            {% endfor %}
        </div>
    </div>
    <div class="tab-pane" id="national">
        <div class="news row ">
            {% for post in posts_nation %}
                <div class="col-sm-3">
                    <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                    {% if post.image %}
                        <img src="{{ post.image.url }}" alt=""/>
                    {% endif %}
                    {{ post.html_content|safe }}
                </div>
            {% endfor %}
        </div>
    </div>

</div>

base/templates/base/agenda_plugin.html
<h1>AGENDA</h1>
<div class="agenda-container">
    {% for event in events %}
        <article class="first-agenda">
        <date>{{ event.start|date:'d-m-Y'}} / {{ event.end|date:'d-m-y'}}</date>
        <h3>{{ event.title }}</h3>
        <p>{{ event.description }}</p>
    </article>
    {% endfor %}

</div>

base/templates/base/all_salles.html
<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true"></script>
<h1>OÙ PRATIQUER</h1>
<article class="map">
 <div  class="test_maps"  id="map-canvas" style="height: 500px;
    max-width: 100%;
    width: 100%; position:relative; ">
     <noscript>
<img src="https://maps.google.com/maps/api/staticmap?size=400x400&zoom=5&center=48.85661,2.35222" alt="">
     </noscript>
    </div>
</article>
   <script type="text/javascript">
        function initialize_map() {
            var mapElem = document.getElementById("map-canvas");
            var locations = {{ markers|safe }};
            var mapOptions = {
                zoom: 6,
                center:  new google.maps.LatLng(48.85661,2.35222),
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };


            var map = new google.maps.Map(mapElem, mapOptions);
            var infowindow = new google.maps.InfoWindow();
            var marker, i;
            for (i = 0; i < locations.length; i++) {
                marker = new google.maps.Marker({
                    position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                    map: map,
                    title: locations[i][0]
                });
                google.maps.event.addListener(marker, 'click', (function(marker, i) {
                    return function() {
                      infowindow.setContent(locations[i][0]+ ' info : <a href="'+locations[i][3]+'">'+locations[i][0]+'</a>');
                      infowindow.open(map, marker);
                    }
                  })(marker, i));
            }

        }


        google.maps.event.addDomListener(window, 'load', initialize_map);

    </script>
{#<img class="img-responsive" alt="Map of {{ map.address }}" src="https://maps.google.com/maps/api/staticmap?center=48.85661,2.35222&zoom={{ zoom }}&markers={{ lat }},{{ long }}&size={{ width }}x{{ height }}&sensor=false">#}

base/templates/base/djangobb_plugin.html
<h1>FORUM</h1>

<div class="list-group">

    {% for post in posts %}

    <a href="{{ post.topic.get_absolute_url }}" class="list-group-item">
        <div class="avatar">
            <img src="img/images/forum-portrait-icon.jpg" alt="">
            <span class="author">{{ post.user.username }}</span>
        </div>
        <p class="forum-post">
            <span class="forum">{{ post.topic.forum }}</span> / <span class="topic">{{ post.topic }}</span> / <span class="post">{{ post.body_html|safe|truncatewords:30 }}</span>
        </p>
    </a>
    {% endfor %}


</div>

base/templates/base/liste_salle.html
{% extends 'base.html' %}
{% load easy_maps_tags sekizai_tags%}
{% block extra_css %}

{% endblock %}

{% block content %}
    <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true"></script>
{% for salle in object.salle_set.all %}
    <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a class="accordion-toggle" data-toggle="" data-parent="#accordion{{ c }}" href="#{{ salle.id }}"> <b><u>{{ salle.nom }}</u></b> : {{ salle.adresse_plain|safe }}
                <span class="glyphicon glyphicon-plus"></span> </a>
                </h4>
            </div>

                <div id="{{ salle.id }}">
                    <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <address>
                            Adresse :
                            {{ salle.adresse|safe }}
                            </address>
                            Horaire :
                            {{ salle.horaire|safe }}
                            <p>
                                Professeur: <br/>

                                {% for professeur in salle.professeurs.all %}
                                      - <strong>{{ professeur.nom|capfirst }}</strong> {{ professeur.prenom|capfirst }} <br/>
                                {% endfor %}


                            </p>
                        {% if salle.description %}
                        <p>Description : <br/>
                            {{ salle.description|safe }}
                        </p>
                        {% endif %}

                        </div>
                        <div class="col-lg-6">
                            <div class="google-map-canvas" id="maps_{{ salle.pk }}" style="height: 100%">
                            {% with salle.adresse_plain as adresse %}
                            {% easy_map adresse 400 300 13 %}
                            {% endwith %}
                            </div>
                        </div>
                    </div>
                </div>
        </div>
        </div>
{% endfor %}

    {% addtoblock 'js' %}

{% endaddtoblock %}
{% endblock %}

base/templates/base/salles.html
{% load easy_maps_tags %}
<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true"></script>
{% block extra_css %}

{% endblock %}

{% regroup salles|dictsort:"ville" by ville as salles_villes %}
{% for salles_ville in salles_villes %}
    <h3>{{ salles_ville.grouper }}</h3>
{% with forloop.counter as c %}
    <div class="panel-group salle" id="accordion{{ c }}" >



    {% for salle in salles_ville.list %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion{{ c }}" href="#{{ salle.id }}"> <b><u>{{ salle.nom }}</u></b> : {{ salle.adresse_plain|safe }}
                <span class="glyphicon glyphicon-plus-sign"></span> </a>
                </h4>
            </div>

                <div id="{{ salle.id }}" class="panel-collapse collapse {% if forloop.first %}{% endif %}">
                    <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <address>
                            Adresse :
                            {{ salle.adresse|safe }}
                            </address>
                            Horaire :
                            {{ salle.horaire|safe }}
                            <p>
                                Professeur: <br/>

                                {% for professeur in salle.professeurs.all %}
                                      - <strong>{{ professeur.nom|capfirst }}</strong> {{ professeur.prenom|capfirst }} <br/>
                                {% endfor %}
                            </p>
                            <p>
                                {{ salle.description|safe }}
                            </p>
                        </div>
                        <div class="col-lg-6">
                            <div class="google-map-canvas" id="maps_{{ salle.pk }}" style="height: 100%">
                            {% with salle.adresse_plain as adresse %}
                            {% easy_map adresse 400 300 13 %}
                            {% endwith %}
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
        {% endfor %}
    {% endwith %}
    </div>
{% endfor %}
<script>
    $(document).ready(function(){
       $(".panel-collapse").each(function(){
           $(this).bind('shown.bs.collapse', function(){
                $('#maps_'+ $(this).attr('id')).children('.test_maps').each(function(){
                    var id = $(this).attr('id').replace('map-canvas-', '');

                    eval('initialize_map_'+ id +'()');
                });
                });
           });
    });
</script>